### ISSUE TITLE
https://your-foursquare-oauth-token.glitch.me is offline now

### ISSUE THREAD

**Issue by sinchang** [dogsheep/swarm-to-sqlite#16]
As title

**Comment by SamClayton** [comment]
I've built a replacement service at [https://wonderful-puddle-pepperberry.glitch.me/](https://wonderful-puddle-pepperberry.glitch.me/) that provides the necessary key. It worked for me with swarm-to-sqlite.

**Comment by SamClayton** [comment]
I've built a replacement service at [https://swarm-api-token-retriever.glitch.me/](https://swarm-api-token-retriever.glitch.me/) that provides the necessary key. It worked for me with swarm-to-sqlite.
